const tabs=document.querySelectorAll('.auth-tabs button'),registerView=document.querySelector('#registerView'),loginView=document.querySelector('#loginView'),roleButtons=document.querySelectorAll('.role-picker button'),registerForm=document.querySelector('#registerForm'),loginForm=document.querySelector('#loginForm');
function show(view){tabs.forEach(t=>t.classList.toggle('active',t.dataset.view===view));registerView.hidden=view!=='register';loginView.hidden=view!=='login'}
tabs.forEach(t=>t.addEventListener('click',()=>show(t.dataset.view)));
function selectRole(role){roleButtons.forEach(b=>b.classList.toggle('active',b.dataset.role===role));registerForm.role.value=role;const talent=role==='talent';document.querySelector('#organizationLabel').firstChild.textContent=talent?'Nama kampus':'Nama usaha';document.querySelector('#organizationLabel input').placeholder=talent?'Contoh: Universitas Brawijaya':'Contoh: Sari Rasa';document.querySelector('.talent-only').hidden=!talent;document.querySelector('#categoryLabel').firstChild.textContent=talent?'Keahlian utama':'Kategori usaha';document.querySelector('#categoryLabel select').innerHTML=talent?'<option>Desain Grafis</option><option>Copywriting</option><option>Video Editing</option>':'<option>Makanan & Minuman</option><option>Fashion</option><option>Retail</option><option>Jasa</option>';registerForm.querySelector('button[type=submit]').textContent=talent?'Buat Akun Talent →':'Buat Akun UMKM →'}
roleButtons.forEach(b=>b.addEventListener('click',()=>selectRole(b.dataset.role)));
async function submit(form,endpoint){const status=form.querySelector('.form-status');status.textContent='Memproses...';status.style.color='';try{const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))}),contentType=response.headers.get('content-type')||'',result=contentType.includes('application/json')?await response.json():{error:`Backend tidak merespons JSON (HTTP ${response.status}). Coba buka /api/health untuk pengecekan.`};if(!response.ok)throw new Error(result.error||'Permintaan gagal.');localStorage.setItem('kalyana_token',result.token);localStorage.setItem('kalyana_user',JSON.stringify(result.user));status.textContent='Berhasil. Mengarahkan ke dashboard...';status.style.color='#287242';setTimeout(()=>location.href='dashboard.html',450)}catch(error){status.textContent=error.message;status.style.color='#aa3030'}}
registerForm.addEventListener('submit',e=>{e.preventDefault();submit(registerForm,'/api/auth/register')});loginForm.addEventListener('submit',e=>{e.preventDefault();submit(loginForm,'/api/auth/login')});
document.querySelectorAll('[data-demo]').forEach(button=>button.addEventListener('click',()=>{const demo=button.dataset.demo;loginForm.email.value=demo==='umkm'?'umkm@kalyana.test':demo==='talent'?'talent@kalyana.test':'admin@kalyana.test';loginForm.password.value=demo==='admin'?'admin234':'demo123'}));
const params=new URLSearchParams(location.search);if(params.get('mode')==='login')show('login');if(params.get('role'))selectRole(params.get('role'));
